application: spaceminesk2013
version: 1
runtime: python
threadsafe: true
api_version: 1

builtins:
- datastore_admin: on

handlers:

- url: /img
  static_dir: img

- url: /data
  static_dir: data

- url: /js
  static_dir: js

- url: /snd
  static_dir: snd


- url: /css
  static_dir: css

- url: .*
  script: main.py


